name: Create AMI


on:
  pull_request:
    branches:
      - main

jobs:
  create-ami:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Setup up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify java version
        run: java -version

      - name: Verify maven version
        run: mvn -version

      - name: Stop MySql
        run: |
          sudo service mysql stop
          sudo apt-get update

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: ${{secrets.DB_PORT}} # Optional, default value is 3306. The port of host
          mysql database: ${{ secrets.DB_NAME}} # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.DB_PASS }}

      - name: Build with Maven
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
        run: mvn clean install

      - name: Create an .env file
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER_WEBAPP}} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_PASS=${{ secrets.DB_USER_WEBAPP }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo FILE_PATH=${{ secrets.FILE_PATH_AMI }} >> .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          profile: dev

      - name: Packer init
        run: packer init ./packer/.

      - name: Packer validate
        run: packer validate ./packer/.

      - name: Packer Build
        run: packer build -var "source_path_jar=target/csye6225-0.0.1-SNAPSHOT.jar" -var "user_name=${{secrets.user_name}}" -var "environment_file=.env" -var "source_ami=${{secrets.debian_id}}" -var "aws_region=${{secrets.aws_region}}" packer/webapp.pkr.hcl



