name: Create AMI


on:
  push:
    branches:
      - main

jobs:
  create-ami:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Setup up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify java version
        run: java -version

      - name: Verify maven version
        run: mvn -version

      - name: Stop MySql
        run: |
          sudo service mysql stop
          sudo apt-get update

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: ${{vars.DB_PORT}}
          mysql database: ${{ vars.DB_NAME}}
          mysql root password: ${{ secrets.DB_PASS }}

      - name: Build with Maven
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ vars.DB_PORT }}
          FILE_PATH: ${{ vars.FILE_PATH }}
          LOG_FILE_PATH: ${{ vars.LOG_FILE_PATH }}
          YOUR_DOMAIN_NAME: ${{ secrets.YOUR_DOMAIN_NAME }}
          API_KEY : ${{ secrets.API_KEY }}
          SG_API_KEY : ${{secrets.SG_API_KEY}}
          TEMPLATE_ID: ${{vars.TEMPLATE_ID}}
        run: mvn clean install


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer init
        run: packer init ./packer/.

      - name: Packer validate
        run: packer validate ./packer/.

      - name: Packer Build
        run: packer build 
              -var "source_path_jar=target/csye6225-0.0.1-SNAPSHOT.jar"  
              -var "source_ami=${{vars.debian_id}}" 
              -var "aws_region=${{vars.aws_region}}" 
              -var "subnet_id=${{vars.subnet_id}}"
              -var "ssh_username=${{vars.ssh_username}}"
              packer/.



