name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name : Verify java version
        run : java -version
        
      - name : Verify maven version
        run : mvn -version

      - name : Stop MySql
        run : |
          sudo service mysql stop
          sudo apt-get update
          
      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: ${{vars.DB_PORT}}
          mysql database: ${{ vars.DB_NAME}}
          mysql root password:  ${{ secrets.DB_PASS }}
      

      - name : Build with Maven
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_PASS : ${{ secrets.DB_PASS }}
          DB_PORT : ${{ vars.DB_PORT }}
          FILE_PATH :  ${{ vars.FILE_PATH }}
          LOG_FILE_PATH : ${{ vars.LOG_FILE_PATH }}
          YOUR_DOMAIN_NAME: ${{ secrets.YOUR_DOMAIN_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run : mvn clean verify


      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports
